/**
 * Standalone production server for Expo deployments.
 *
 * Serves three things from a single HTTP port:
 *   1. The browser web app (expo export --platform web → static-build/web/),
 *      including SPA-style fallback to index.html for unknown routes.
 *   2. The Expo Go OTA manifest (when the request carries an
 *      `expo-platform: ios|android` header) and the platform JS bundles +
 *      assets generated by scripts/build.js into static-build/<timestamp>/.
 *   3. The QR-code install landing page at /expo-go (so users who want to
 *      preview the native app in Expo Go can still get the QR code).
 *
 * Zero external dependencies — uses only Node.js built-ins (http, fs, path).
 */

const http = require("http");
const fs = require("fs");
const path = require("path");

const STATIC_ROOT = path.resolve(__dirname, "..", "static-build");
const WEB_ROOT = path.join(STATIC_ROOT, "web");
const TEMPLATE_PATH = path.resolve(__dirname, "templates", "landing-page.html");
const basePath = (process.env.BASE_PATH || "/").replace(/\/+$/, "");

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

const hasWebBuild = fs.existsSync(path.join(WEB_ROOT, "index.html"));

function getAppName() {
  try {
    const appJsonPath = path.resolve(__dirname, "..", "app.json");
    const appJson = JSON.parse(fs.readFileSync(appJsonPath, "utf-8"));
    return appJson.expo?.name || "App Landing Page";
  } catch {
    return "App Landing Page";
  }
}

function serveManifest(platform, res) {
  const manifestPath = path.join(STATIC_ROOT, platform, "manifest.json");

  if (!fs.existsSync(manifestPath)) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(
      JSON.stringify({ error: `Manifest not found for platform: ${platform}` }),
    );
    return;
  }

  const manifest = fs.readFileSync(manifestPath, "utf-8");
  res.writeHead(200, {
    "content-type": "application/json",
    "expo-protocol-version": "1",
    "expo-sfv-version": "0",
  });
  res.end(manifest);
}

function serveLandingPage(req, res, landingPageTemplate, appName) {
  const forwardedProto = req.headers["x-forwarded-proto"];
  const protocol = forwardedProto || "https";
  const host = req.headers["x-forwarded-host"] || req.headers["host"];
  const baseUrl = `${protocol}://${host}`;
  const expsUrl = `${host}`;

  const html = landingPageTemplate
    .replace(/BASE_URL_PLACEHOLDER/g, baseUrl)
    .replace(/EXPS_URL_PLACEHOLDER/g, expsUrl)
    .replace(/APP_NAME_PLACEHOLDER/g, appName);

  res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
  res.end(html);
}

function serveFile(filePath, res) {
  const ext = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[ext] || "application/octet-stream";
  const content = fs.readFileSync(filePath);
  // Hashed JS/CSS/assets are safe to cache aggressively; HTML must not be cached.
  const isHtml = ext === ".html";
  const cacheControl = isHtml
    ? "no-store, no-cache, must-revalidate"
    : "public, max-age=31536000, immutable";
  res.writeHead(200, {
    "content-type": contentType,
    "cache-control": cacheControl,
  });
  res.end(content);
}

function tryServeFromRoot(root, urlPath, res) {
  if (!fs.existsSync(root)) return false;
  const safePath = path.normalize(urlPath).replace(/^(\.\.(\/|\\|$))+/, "");
  const filePath = path.join(root, safePath);
  if (!filePath.startsWith(root)) {
    res.writeHead(403);
    res.end("Forbidden");
    return true;
  }
  if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
    return false;
  }
  serveFile(filePath, res);
  return true;
}

function serveSpaFallback(res) {
  const indexPath = path.join(WEB_ROOT, "index.html");
  if (!fs.existsSync(indexPath)) {
    res.writeHead(404);
    res.end("Not Found");
    return;
  }
  serveFile(indexPath, res);
}

const landingPageTemplate = fs.readFileSync(TEMPLATE_PATH, "utf-8");
const appName = getAppName();

const server = http.createServer((req, res) => {
  const url = new URL(req.url || "/", `http://${req.headers.host}`);
  let pathname = url.pathname;

  if (basePath && pathname.startsWith(basePath)) {
    pathname = pathname.slice(basePath.length) || "/";
  }

  const platform = req.headers["expo-platform"];
  const isExpoClient = platform === "ios" || platform === "android";

  // 1) Expo Go native manifest endpoint.
  if (isExpoClient && (pathname === "/" || pathname === "/manifest")) {
    return serveManifest(platform, res);
  }

  // 2) Native bundles + assets live under static-build/<timestamp>/...
  //    These paths look like /<timestamp>/_expo/static/js/<platform>/bundle.js
  //    Try the static-build root first.
  if (pathname !== "/" && tryServeFromRoot(STATIC_ROOT, pathname, res)) {
    return;
  }

  // 3) QR-code install landing page (explicit opt-in).
  if (pathname === "/expo-go" || pathname === "/expo-go/") {
    return serveLandingPage(req, res, landingPageTemplate, appName);
  }

  // 4) Browser web app — serve from static-build/web/.
  if (hasWebBuild) {
    if (pathname === "/" && tryServeFromRoot(WEB_ROOT, "/index.html", res)) {
      return;
    }
    if (tryServeFromRoot(WEB_ROOT, pathname, res)) return;
    // SPA fallback for client-side routes (no file extension).
    if (!path.extname(pathname)) {
      return serveSpaFallback(res);
    }
    res.writeHead(404);
    res.end("Not Found");
    return;
  }

  // 5) No web build available — fall back to QR landing page at /.
  if (pathname === "/") {
    return serveLandingPage(req, res, landingPageTemplate, appName);
  }

  res.writeHead(404);
  res.end("Not Found");
});

const port = parseInt(process.env.PORT || "3000", 10);
server.listen(port, "0.0.0.0", () => {
  console.log(
    `Serving on port ${port} ` +
      (hasWebBuild
        ? "— web app at /, QR install at /expo-go"
        : "— web build missing; QR install at /"),
  );
});
